development:
  adapter: postgresql
  database: safety_dance_development
  encoding: unicode
  host: /private/tmp

production:
  adapter: postgresql
  database: safety_dance_production
  encoding: unicode
  host: /private/tmp
